stages:
  - build
  - test
  - deploy
  - status

variables:
  JAR_FILE: "target/freelance-*.jar"
  DEV_USER: "back"
  DEV_HOST: "172.31.250.128"
  DEV_PATH: "/home/back/freelance.jar"
  DEV_PASSWORD: "back"

cache:
  paths:
    - ~/.m2/repository  # Cache des dépendances Maven pour accélérer le build

# Étape de build
build-job:
  stage: build
  tags:
    - local
  script:
    - mvn clean package -DskipTests  # Compile sans exécuter les tests
  artifacts:
    paths:
      - $JAR_FILE

# Étape de test
test-job:
  stage: test
  tags:
    - local
  dependencies:
    - build-job
  script:
    - mvn test  # Exécute les tests
  artifacts:
    paths:
      - target/surefire-reports/*.xml
      - target/surefire-reports/*.txt
    reports:
      junit: target/surefire-reports/*.xml

# Étape de déploiement
deploy-job:
  stage: deploy
  tags:
    - local
  dependencies:
    - build-job
  script:
    - apt-get update -qq && apt-get install -qqy sshpass  # Installation de sshpass si nécessaire
    - sshpass -p "$DEV_PASSWORD" scp -o StrictHostKeyChecking=no $JAR_FILE $DEV_USER@$DEV_HOST:$DEV_PATH
    # Vérifie si le service est déjà en cours d'exécution et le redémarre uniquement si nécessaire
    - sshpass -p "$DEV_PASSWORD" ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_HOST "sudo systemctl is-active --quiet freelance && sudo systemctl restart freelance || sudo systemctl start freelance"
  only:
    - master
  before_script:
    - echo "Déploiement en cours..."
  after_script:
    - echo "Déploiement terminé."

# Étape de vérification de l'exécution
status-check:
  stage: status
  tags:
    - local
  script:
    - echo "Vérification de l'état du service freelance..."
    - sshpass -p "$DEV_PASSWORD" ssh -o StrictHostKeyChecking=no $DEV_USER@$DEV_HOST "sudo systemctl status freelance"  # Vérifie l'état du service
    - echo "Vérification terminée."
  only:
    - master
