stages:
  - build
  - test
  - deploy
  - run

variables:
  JAR_FILE: "target/freelance-0.0.1-SNAPSHOT.jar"
  REMOTE_USER: "back"
  REMOTE_HOST: "172.31.250.128"
  REMOTE_PATH: "/home/back/freelance.jar"
  REMOTE_PASSWORD: "back"

cache:
  paths:
    - ~/.m2/repository  # Cache des dépendances Maven pour accélérer le build

# Étape de build
build-job:
  stage: build
  tags:
    - local
  script:
    - mvn clean package -DskipTests  # Compile sans exécuter les tests
  artifacts:
    paths:
      - $JAR_FILE
  only:
    - master

# Étape de test
test-job:
  stage: test
  tags:
    - local
  dependencies:
    - build-job
  script:
    - mvn test  # Exécute les tests

# Étape de déploiement
deploy-job:
  stage: deploy
  tags:
    - local
  environment:
    name: production
  dependencies:
    - build-job
  script:
    - apt-get update -qq && apt-get install -qqy sshpass  # Installation de sshpass si nécessaire
    - sshpass -p "$REMOTE_PASSWORD" scp -o StrictHostKeyChecking=no $JAR_FILE $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
    # Vérifie si le service est déjà en cours d'exécution et le redémarre uniquement si nécessaire
    - sshpass -p "$REMOTE_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo systemctl is-active --quiet freelance && sudo systemctl restart freelance || sudo systemctl start freelance"
  only:
    - master
  before_script:
    - echo "Déploiement en cours..."
  after_script:
    - echo "Déploiement terminé."

# Étape de vérification de l'exécution
run-check:
  stage: run
  tags:
    - local
  script:
    - sshpass -p "$REMOTE_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo systemctl status freelance"  # Vérifie l'état du service
  only:
    - master
