spring:
  datasource:
    url: jdbc:postgresql://172.31.253.108:5432/dev_freelance
    username: dev_freelance_user
    password: freelance
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    com.example.freelance: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: null

server:
  port: 9091
